version: "3.9"

services:
  budesk_db:
    image: postgres:17
    container_name: budesk_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budesk
      POSTGRES_USER: budesk
      POSTGRES_PASSWORD: budesk
    volumes:
      - budesk_data:/var/lib/postgresql/data

volumes:
  budesk_data:
